[build]
  functions = "functions"
  # This will be run the site build
  command = "gatsby build"
  # This is the directory is publishing to netlify's CDN
  publish = "public"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
